config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products 

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  
  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

	before_save :format_name

	has_many :reviews
  	has_many :users, through: :reviews

	validates :description, :name, presence: true
	validates :price_in_cents, numericality: {only_integer: true}
	
	def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
    end

    private 
    def format_name
    	self.name = name.titleize
    end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
  	belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	#attr_accessor :password
	#attr_accessor :password_confirmation

	#def authenticate
	# secret
	#end

	validates :name, presence: true
	#validates :password, confirmation: true
	
	has_many :reviews
  	has_many :products, through: :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
     @products = if params[:search]
      Product.where("name ILIKE ?", "%#{params[:search]}%").page(params[:page])
    else
      Product.all.page(params[:page])
    end

    respond_to do |format|
      format.html 
      format.js # render 'index.js.erb'
    end
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end

    # render show
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :load_product
	before_action :ensure_logged_in, only: [:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      respond_to do |format|
        format.html do
          redirect_to product_path(@review.product), notice: 'Review created successfully'
        end
        format.js   # create.js.erb
      end
    else
      render 'products/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to products_url, notice: "Signed up!"
  	else
  		render "new"
  end
end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header id="site-header">
      <h1>Rainforest</h1>
      <div class="page-entries">
        <%= page_entries_info @products if @products %>
      </div>
    </header>

    <main>
      <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
      <% end %>

      <p class="userinfo">
        <% if current_user %>
          Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
        <% else %>
          <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        <% end %>
      </p>

      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<!-- <form action="http://google.com">
    <input type="submit" value="Go to Google">
</form> -->

app/views/products/_product.html.erb
<li class="product">
  <%= link_to product_path(product.id) do %>
   <h2>
     <%= number_to_currency(product.formatted_price) %>
     <%= product.name %>
   </h2>
  <% end %>
  <!-- keeps the description to 100 characters or less -->
  <p><%= truncate(product.description, length: 100) %></p>
</li>s

app/views/products/edit.html.erb
<!-- <h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p> -->

<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= link_to 'New Product', new_product_path %>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<div id="products">
  <%= render @products %>
</div>

<p class="page-entries"><%= page_entries_info @products %></p>

<%= paginate @products %>

app/views/products/index.js.erb
$('#products').html("<%= j(render @products) %>");

app/views/products/new.html.erb
<!-- <h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p> -->

<h1>New Product</h1>

<%= render 'form' %>

<br><br><br>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!-- <h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p> -->


<h3>Products</h3>


  <p><%= @product.name %><br /> 

  	<%= @product.description %><br /> 

  <%= @product.formatted_price %><br /></p>

  <%= link_to 'Edit', edit_product_path(@product)
%> | <%= link_to 'Delete', @product, method: :delete %>

<<h3>Reviews</h3>

<p>Reviews for <%= @product.name %></p>

<div class="review-list">
  <%= render :partial => 'reviews/review', :collection => @product.reviews %>
</div>

<% if current_user %>
  <h4>New Review</h4>

  <%= form_for([@product, @review], :remote => true) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/_review.html.erb
<p>
  <%= review.comment %>
  <br>
  <% if review.user != nil %>
    <em> by <%= review.user.email %></em>
    Added on: <%= review.created_at %>
  <% end %>
</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
$('.review-list').append('<%= j(render @review) %>');
$('#review_comment').val('');

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<!-- <h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
 -->

 <h1>Sign Up</h1>

 <%= form_for @user do |f| %>
<% if @user.errors.any? %>
<div class="error_messages">
	<h2>Form is invalid</h2>
	<ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>






 